.TH EDTCABINST 1
.SH NAME
edtcabinst \- install haskell cabal packages
.SH SYNOPSIS
\fBedtcabinst \-h
.br
.SH DESCRIPTION
.B edtcabinst
Install a haskell cabal package on cygwin servers
.SH OPTIONS
.TP
\fB\-h
Shows the help info.
.TP
\fB\-v
Shows the current version.
.TP
\fB\-w
Overwrite a previous installed file
.SH Authors
Juan Francisco Cardona McCormick <fcardona@eafit.edu.co>
