.TH ETGETREPOS 1
.SH NAME
etgetrepos \- gets a sudent repository from internet
.SH SYNOPSIS
\fBedtgetrepos \-h
.br
\fBedtgetrepos \fR[\fB\-u\fR|\fB\-n\fR|\fB\-r\fR]
.SH DESCRIPTION
.B edtgetrepos
Downloads a repository from a version control over internet
and creates needed directories for the course
.SH OPTIONS
.TP
\fB\-h
Display usage of edtgetrepos.
.TP
\fB\-u
Version control to use
.TP
\fB\-n
Username to use in the version control
.TP
\fB\-r
Repository name in the version control
.SH Author
Juan Francisco Cardona McCormick <fcardona@eafit.edu.co>
.br
Andres Felipe Ortega Montoya <aortega7@eafit.edu.co>
