.TH ETGETREPOS 1
.SH NAME
etgetrepos \- gets a student repository
.SH SYNOPSIS
.B etgetrepos
[\fB\-h]
[\fB\-l|\fB\-w|\fB\-t|\fB\-p] \fIn
.SH DESCRIPTION
.B etgetrepos
gets a student repository from different sources
.SH OPTIONS
.TP
\fB\-h
Display the help option.
.TP
\fB\-l=\fIn
Creates the directory needed for a new lecture \fIn
.TP
\fB\-w=\fIn
Creates the directory needed for a new workshop \fIn
.TP
\fB\-t=\fIn
Creates the directory needed for a new test \fIn
.TP
\fB\-p=\fIn
Creates the directory needed for a new project \fIn
.SH Files
.I ~/.edtrc
.RS
Student configuration. See
.BR edtrc(5)
for futher details.
.SH Author
Juan Francisco Cardona McCormick <fcardona@eafit.edu.co>
.br
Andres Felipe Ortega Montoya <aortega7@eafit.edu.co>
