.TH ETGETREPOS 1
.SH NAME
etgetrepos \- gets a student repository
.SH SYNOPSIS
.B etgetrepos
[\fB\-h]
.SH DESCRIPTION
.B etgetrepos
gets a student repository from different sources, it depends on 
.SH OPTIONS
.TP
.BR \-h
Display the help option.
.SH Files
.I ~/.edtrc
.RS
Student configuration. See
.BR edtrc(5)
for futher details.
.SH Author
Juan Francisco Cardona McCormick < fcardona at eafit dot edu dot co >

