.TH EDTRRINITSCRIPT 1
.SH NAME
edtrrinitscript \- re-run the init script of EAFIT Dis Tools
.SH SYNOPSIS
\fBedtrrinitscript \-h
.br
.SH DESCRIPTION
.B edtrrinitscript
Re-run the init script of the course in order to re-install those tools require for each course.
.SH OPTIONS
.TP
\fB\-h
Shows the help info.
.TP
\fB\-v
Shows the current version.
.SH Authors
Juan Francisco Cardona McCormick <fcardona@eafit.edu.co>
