.TH EDTSETEVALUNIT 1
.SH NAME
edtsetevalunit \- sets the current eval unit
.SH SYNOPSIS
.B edtgetrepos -h
.PP
.B edtgetrepos [-l|-t|-w] -n \fInumber
.PP
.B edtgetrepos -p [-d] -n \fIproject-name
.SH DESCRIPTION
.B edtsetevalunit
creates and sets the current eval unit in the user repository
.SH OPTIONS
.TP
.BR \-h
Prints the help
.TP
.BR \-l
Select Lecture eval unit
.TP
.BR \-t
Select Test eval unit
.TP
.BR \-w
Select Workshop eval unit
.TP
.BR -n
\fInumber
.TP
.BR \-p
Select Project eval unit
.TP
.BR -d
Write proyect unit into Disk
.TP
.BR -n
\fIproyect-name
.SH Files
.I ~/.edtrc
.RS
Student configuration. See
.BR edtrc(5)
for futher details.
.SH Author
Juan Francisco Cardona McCormick <fcardona@eafit.edu.co>
.br
Sebastian Patiño Barrientos <spatino6@eafit.edu.co>
